import oracledb

try:
    # Connect to the specific pluggable database 'MYPDB'
    connection = oracledb.connect(
        user='admin',                # Replace with your actual username
        password='your_password',    # Replace with your actual password
        dsn='localhost:1521/MYPDB'    # Connect directly to your PDB; ensure the PDB name matches
    )
    print("Connected successfully to the 'MYPDB' database.")
    cursor = connection.cursor()

    # SQL to create the 'reviews' table if it doesn't exist
    create_table_sql = """
    BEGIN
        EXECUTE IMMEDIATE '
            CREATE TABLE reviews (
                review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                reviewer_name VARCHAR2(50),
                review_text VARCHAR2(200),
                rating NUMBER(1, 0) CHECK (rating BETWEEN 1 AND 5),
                review_date DATE DEFAULT SYSDATE
            )
        ';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN  -- ORA-00955: name is already used by an existing object
                RAISE;
            END IF;
    END;
    """

    cursor.execute(create_table_sql)
    print("Table 'reviews' is ready.")

except oracledb.DatabaseError as e:
    error_obj, = e.args
    print(f"Database error occurred: {error_obj.message}")

except Exception as e:
    print(f"An unexpected error occurred: {e}")

finally:
    # Close cursor and connection
    if 'cursor' in locals():
        cursor.close()
    if 'connection' in locals():
        connection.close()
        print("Connection closed.")